@extends('layouts.app')

@section('title', 'Industries We Serve | ProPresence Digital')
@section('meta_description', 'Industry-specific digital growth expertise from SaaS to DTC, fintech to creators.')

@section('content')
<section class="hero"><div class="container"><span class="eyebrow">Industries</span><h1>Vertical depth, not just horizontal skill.</h1><p class="lead" style="max-width:720px">We bring category-specific playbooks and benchmarks to every engagement.</p></div></section>
<section class="block"><div class="container"><div class="grid cols-3"><div class="card"><h3>SaaS & B2B Tech</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>E-commerce & DTC</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Fintech</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Healthcare & Wellness</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Real Estate</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Education & EdTech</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Professional Services</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Hospitality</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Manufacturing</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Web3 & AI Startups</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Media & Entertainment</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div><div class="card"><h3>Creators & Personal Brands</h3><p>Vertical playbooks, benchmarks and creative tuned to how buyers in this space actually decide.</p></div></div></div></section>
@endsection
